### ISSUE TITLE
Java Port

### ISSUE THREAD

**Issue by pjr1060** [ayende/Xiao#1]
Hi Ayende - thanks for your great work generalising Smaz.   Please find attached a Java port if you'd like to add that to this project.  I modified the term map for our requirement to compress MimeTypes.

Thanks again,

Peter
[XiaoMime.java.txt](https://github.com/ayende/Xiao/files/100971/XiaoMime.java.txt)

**Comment by ayende** [comment]
Can you turn that into a PR? With a single Java file that people can us?

**Comment by ayende** [comment]
Merged
